baseURL = "/"
languageCode = "en-us"
title = "Amos Cheruiyot"
theme = "minimal"
googleAnalytics = ""


[params]
    author = "Amos Cheruiyot"
    description = "Web Dev Enthusiast & Techie"
    githubUsername = "murdhawke"
    accent = "green"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 3


# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "amoscheruiyot22@gmail.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/murdhawke/"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/murdhawke/"
    name = "twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/murdhawke/"
    name = "linkedin"
    weight = 4

[[menu.icon]]
    url = "https://stackoverflow.com/users/5805468/amos-cheruiyot"
    name = "stack-overflow"
    weight = 5
